Improve config file handling in openwrt-ci.yml
Added error handling for missing config file in CI workflow.

diff --git a/.github/workflows/openwrt-ci.yml b/.github/workflows/openwrt-ci.yml
--- a/.github/workflows/openwrt-ci.yml
+++ b/.github/workflows/openwrt-ci.yml
@@ -52,7 +52,18 @@ jobs:
         run: |
           pwd
           ls
-          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE .config
+          if [ -e "$CONFIG_FILE" ]; then
+              echo "Using config file: $CONFIG_FILE"
+              mv "$CONFIG_FILE" .config
+          else
+              echo "ERROR: Config file '$CONFIG_FILE' not found!"
+              exit 1
+          fi
+          echo "mv config file after list:"
+          ls
+
+
+          exit 1
 
           ./scripts/feeds update -a
           ./scripts/feeds install -a
